#!/bin/bash
set -e

if [ -n "$TZ" ]; then
    # Configure PHP to use $TZ variable.
    sed -i "/date\.timezone =/c\date.timezone = $TZ" /etc/php5/cli/php.ini /etc/php5/apache2/php.ini
fi

exec apache2 -DFOREGROUND