#!/bin/bash
set -e

# Allow a specific timezone to be set and passed into PHP
if [ -n "$TZ" ]; then
    # Configure PHP to use $TZ variable.
    sed -i "/date\.timezone =/c\date.timezone = $TZ" /etc/php5/cli/php.ini /etc/php5/apache2/php.ini
fi

# Allow the apache user to be given a specific UID.
if [ -n "$APACHE_RUN_UID" ]; then
    # id -u ubuntu - Will output user id for a username
    getent passwd "$APACHE_RUN_USER" > /dev/null
    if [ $? -eq 0 ]; then
        # User exists, switch the uid.
        usermod -u "$APACHE_RUN_UID" $APACHE_RUN_USER
    else
        adduser --uid "$APACHE_RUN_UID" $APACHE_RUN_USER
    fi
fi

# Allow a script to run on startup.
if [ -x "/on-docker-boot" ]; then
  /on-docker-boot
fi

exec apache2 -DFOREGROUND