
FROM debian:jessie

# common-php56
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_PID_FILE /var/run/apache2.pid
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2

RUN apt-get update \
  # Install base deps:
  && apt-get install -y --force-yes bzip2 curl git mysql-client \
  # Install php
  && apt-get install -y --force-yes apache2 php5 php5-curl php5-mysqlnd php5-gd php5-sqlite php5-mcrypt \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Configure Apache
RUN a2enmod rewrite php5 \
  # Redirect Apache logging to stdout and stderr for capture using
  # docker mechanisms.
  && ln -sf /dev/stdout /var/log/apache2/access.log \
  && ln -sf /dev/stderr /var/log/apache2/error.log \
  && echo "opcache.memory_consumption = 128" >> /etc/php5/mods-available/opcache.ini

# Install CLI tools:
RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/bin/composer \
  && mkdir /usr/share/composer \
  && cd /usr/share/composer \
  && composer init --no-interaction && composer config bin-dir /usr/local/bin \
  && composer require drush/drush --prefer-dist \
  && rm -r /root/.composer/cache

# Configure:
ADD apache-vhost.conf /etc/apache2/sites-available/000-default.conf
ADD apache2-foreground /usr/local/bin/

WORKDIR /var/www
EXPOSE 80

CMD ["apache2-foreground"]
# /common-php56

# Install nodejs
ENV NVM_DIR=$HOME/.nvm
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash \
  && . $NVM_DIR/nvm.sh \
  && nvm install node \
  && npm install -g gulp phantomjs-prebuilt \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY test-dev.sh /test.sh
