
FROM php:5.6-apache

# common-php56
ENV DEBIAN_FRONTEND noninteractive
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data

RUN apt-get update && apt-get install -y --no-install-recommends \
      # for bz2
      bzip2 libbz2-dev \
      # for ftp
      libssl-dev \
      # for gd
      libfreetype6-dev libjpeg62-turbo-dev libpng12-dev \
      # for intl
      libicu-dev \
      # for dom
      libxml2-dev \
      # for ldap
      libldap2-dev \
      # for mcrypt
      libmcrypt-dev \
      # for mysql
      mysql-client \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu \
    && docker-php-ext-install -j$(nproc) \
      bcmath \
      bz2 \
      calendar \
      exif \
      ftp \
      gd \
      gettext \
      intl \
      ldap \
      mcrypt \
      mysql \
      mysqli \
      opcache \
      pcntl \
      pdo_mysql \
      shmop \
      soap \
      sockets \
      sysvmsg \
      sysvsem \
      sysvshm \
      zip

# Configure Apache:
RUN a2enmod rewrite \
  && sed -i "/User www-data/c\User \$\{APACHE_RUN_USER\}" /etc/apache2/apache2.conf \
  && sed -i "/Group www-data/c\Group \$\{APACHE_RUN_GROUP\}" /etc/apache2/apache2.conf \
  # Preemptively add a user 1000, for use with $APACHE_RUN_USER on osx
  && adduser --uid 1000 --gecos 'My OSX User' --disabled-password osxuser

# Install CLI tools:
RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/bin/composer \
  && mkdir /usr/share/composer \
  && cd /usr/share/composer \
  && composer init --no-interaction && composer config bin-dir /usr/local/bin \
  && composer require drush/drush --prefer-dist \
  && rm -r /root/.composer/cache

ADD apache2-foreground /usr/local/bin/apache2-foreground-enhanced
CMD ["apache2-foreground-enhanced"]
# /common-php56

# Install development tools:
ENV PATH=/usr/share/node:$PATH
ENV NVM_DIR=$HOME/.nvm
RUN apt-get update \
  # Nodejs
  && curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash \
  && . $NVM_DIR/nvm.sh \
  && nvm install node \
  && ln -s $NVM_DIR/versions/node/`nvm version node`/bin /usr/share/node \
  # gulp and phantomjs
  && apt-get install -y libfontconfig \
  && npm install -g gulp phantomjs-prebuilt \
  && npm cache clean \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY test-dev.sh /test.sh
