
FROM debian:jessie

# common-php70
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_PID_FILE /var/run/apache2.pid
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2

RUN apt-get update \
  # Install base deps:
  && apt-get install -y --force-yes curl git mysql-client \
  # Install dotdeb repo:
  && curl http://www.dotdeb.org/dotdeb.gpg | apt-key add - \
  && echo "deb http://packages.dotdeb.org jessie all\ndeb-src http://packages.dotdeb.org jessie all" > /etc/apt/sources.list.d/dotdeb-php55.list \
  && apt-get update \
  # Install php
  && apt-get install -y --force-yes apache2 php7.0 php7.0-curl php7.0-mysql php7.0-gd php7.0-sqlite3 php7.0-mcrypt \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Configure Apache
RUN a2enmod rewrite php7.0 \
  # Redirect Apache logging to stdout and stderr for capture using
  # docker mechanisms.
  && ln -sf /dev/stdout /var/log/apache2/access.log \
  && ln -sf /dev/stderr /var/log/apache2/error.log \
  && echo "opcache.memory_consumption = 128" >> /etc/php/mods-available/opcache.ini

## Install CLI tools:
RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/bin/composer \
  && mkdir /usr/share/composer \
  && cd /usr/share/composer \
  && composer init --no-interaction && composer config bin-dir /usr/local/bin \
  && composer require drush/drush --prefer-dist \
  && rm -r /root/.composer/cache

# Configure:
ADD apache-vhost.conf /etc/apache2/sites-available/000-default.conf
ADD apache2-foreground /usr/local/bin/

WORKDIR /var/www
EXPOSE 80

CMD ["apache2-foreground"]
# /common-php70

COPY test-dev.sh /test.sh