
FROM debian:wheezy

# common-php55
ENV DEBIAN_FRONTEND noninteractive
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_PID_FILE /var/run/apache2.pid
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2

RUN echo "deb http://http.debian.net/debian wheezy-backports main" >> /etc/apt/sources.list \
  && apt-get update \
  # Install base deps:
  && apt-get install -y -t wheezy-backports git \
  && apt-get install -y --force-yes bzip2 curl mysql-client \
  # Install dotdeb repo:
  && curl http://www.dotdeb.org/dotdeb.gpg | apt-key add - \
  && echo "deb http://packages.dotdeb.org wheezy-php55 all\ndeb-src http://packages.dotdeb.org wheezy-php55 all" > /etc/apt/sources.list.d/dotdeb-php55.list \
  && apt-get update \
  # Install PHP
  && apt-get install -y --force-yes apache2 php5 php5-curl php5-mysqlnd php5-gd php5-sqlite php5-mcrypt \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Configure Apache:
RUN a2enmod rewrite php5 \
  # Redirect Apache logging to stdout and stderr for capture using
  # docker mechanisms.
  && ln -sf /dev/stdout /var/log/apache2/access.log \
  && ln -sf /dev/stderr /var/log/apache2/error.log \
  && echo "opcache.memory_consumption = 128" >> /etc/php5/mods-available/opcache.ini

# Install CLI tools:
RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/bin/composer \
  && mkdir /usr/share/composer \
  && cd /usr/share/composer \
  && composer init --no-interaction && composer config bin-dir /usr/local/bin \
  && composer require drush/drush --prefer-dist \
  && rm -r /root/.composer/cache

# Configure:
ADD apache-vhost.conf /etc/apache2/sites-enabled/000-default
ADD apache2-foreground /usr/local/bin/

WORKDIR /var/www
EXPOSE 80

CMD ["apache2-foreground"]
# /common-php55

# Install nodejs
ENV NVM_DIR=$HOME/.nvm
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash \
  && . $NVM_DIR/nvm.sh \
  && nvm install node \
  && npm install -g gulp phantomjs-prebuilt \
  && npm cache clean \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY test-dev.sh /test.sh
